packaging_format = 2

id = "simplytranslate"
name = "Simply Translate"
description.en = "Web interface for many translation engine"
description.fr = "Interface Web pour de nombreux moteurs de traduction"
description.id = "Antarmuka web mesin penerjemahan"

version = "2023.12.19~ynh1"

maintainers = ["the7thNightmare"]

[upstream]
license = "AGPL-3.0"
website = "https://simplytranslate.org/"
code = "https://codeberg.org/ManeraKai/simplytranslate"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "100M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/simplytranslate"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]

        [resources.sources.main]
        url = "https://codeberg.org/ManeraKai/simplytranslate/archive/fb218989fffde85edfdde930618dd7e9c6112eb5.tar.gz"
        sha256 = "8edb0fb413c1776f291f4c6990a944ab3e0f5dbfa2d80450a33c12b77a82cfd2"
        in_subdir = true

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
